export {wxHttpClient, RequestAction} from "./wxhttpclient"
export {wxSession} from "./wxsession"
export {wxStorage} from "./wxstorage"
export {wxTip} from "./wxtips"
export {wxSetting, WxScope} from "./wxsetting"
export {wxShare} from "./wxshare"
export {wxGetLaunchOptions, WxLaunchOptions} from "./wxfuncs"